// city with popular area 
export const cityAreaData = {
  Mumbai: [
    "Mira Road East",
    "Chembur",
    "Andheri West",
    "Malad West",
    "Borivali West",
    "Kandivali West",
    "Andheri East",
    "Virar West",
    "Thane West",
    "Kandivali East",
  ],
  Pune: [
    "Ravet",
    "Wakad",
    "Baner",
    "Wagholi",
    "Hadapsar",
    "Kharadi",
    "Punawale",
    "Tathawade",
    "Kothrud",
    "Hinjawadi",
  ],
  Thane: [
    "Thane West",
    "Dombivli East",
    "Kalyan West",
    "Badlapur East",
    "Bhiwandi",
    "Ambernath East",
    "Badlapur West",
    "Kalyan East",
    "Karjat",
    "Dombivli West",
  ],
  Nagpur: [
    "Jamtha",
    "Manish Nagar",
    "Besa",
    "Mihan",
    "Hingna",
    "Manewada",
    "Shankarpur",
    "Zingabai Takli",
    "Beltarodi",
    "Pipla",
  ],
};

export const TypeOfProperty = [
  { id: "land", value: "open land ( with out boundry)" },
  { id: "plot", value: "open plot (with boundry)" },
  { id: "gala", value: "gala" },
  { id: "commercial", value: "commercial" },
  { id: "shop", value: "shop" },
  { id: "commercial office", value: "commercial office" },
];